'use strict';
/**
 * Assembles the browser client into a single `www/` directory for Capacitor.
 *
 * The server normally mounts each top-level folder at its own URL prefix
 * (see server/index.js), so index.html references "/style.css", "/game/…",
 * "/assets/…" etc. This script reproduces that exact URL layout on disk so
 * the same HTML works unchanged inside the native WebView.
 *
 * It also rewrites the two things that only work when the page is served by
 * our own server:
 *   1. window.PR_SERVER — the API/socket origin. Empty on web (same origin),
 *      set to the deployed URL in the native build.
 *   2. the /socket.io/socket.io.js script tag, which is generated by the
 *      Socket.io server and has to be loaded from that server in the app.
 *
 * Usage: node scripts/build-www.js [serverOrigin]
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WWW = path.join(ROOT, 'www');
const SERVER_ORIGIN = (process.argv[2] || '').replace(/\/$/, '');

/** ui/ becomes the web root; everything else keeps its server-side URL prefix. */
const COPY_PLAN = [
  { from: 'ui', to: '.' },
  { from: 'game', to: 'game' },
  { from: 'assets', to: 'assets' },
  { from: 'worlds', to: 'worlds' },
  { from: 'characters', to: 'characters' },
  { from: 'multiplayer', to: 'multiplayer' },
];

function copyDir(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

fs.rmSync(WWW, { recursive: true, force: true });
fs.mkdirSync(WWW, { recursive: true });

for (const { from, to } of COPY_PLAN) {
  const srcDir = path.join(ROOT, from);
  if (!fs.existsSync(srcDir)) throw new Error(`Missing source directory: ${from}`);
  copyDir(srcDir, path.join(WWW, to));
}

// --- rewrite index.html for the native origin -------------------------------
const indexPath = path.join(WWW, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');

const configScript = `<script>window.PR_SERVER = ${JSON.stringify(SERVER_ORIGIN)};</script>`;

if (SERVER_ORIGIN) {
  // In the app the Socket.io client library must come from the real server.
  html = html.replace(
    '<script src="/socket.io/socket.io.js"></script>',
    `${configScript}\n<script src="${SERVER_ORIGIN}/socket.io/socket.io.js"></script>`
  );
} else {
  html = html.replace(
    '<script src="/socket.io/socket.io.js"></script>',
    `${configScript}\n<script src="/socket.io/socket.io.js"></script>`
  );
}

if (!html.includes('window.PR_SERVER')) {
  throw new Error('Failed to inject PR_SERVER — the socket.io script tag was not found in index.html');
}
fs.writeFileSync(indexPath, html, 'utf8');

const fileCount = (function count(dir) {
  return fs.readdirSync(dir, { withFileTypes: true })
    .reduce((n, e) => n + (e.isDirectory() ? count(path.join(dir, e.name)) : 1), 0);
})(WWW);

console.log(`built www/ — ${fileCount} files, server origin: ${SERVER_ORIGIN || '(same origin)'}`);
